import { NextResponse } from 'next/server';
import Stripe from 'stripe';
import { generateLicenseKey } from '@/utils/licenseGenerator';
import { saveLicense } from '@/lib/licenses';

// Initialize Stripe with your secret key from environment variable
const stripeSecretKey = process.env.STRIPE_SECRET_KEY;
const endpointSecret = process.env.STRIPE_WEBHOOK_SECRET || '';

if (!stripeSecretKey) {
  console.error('Missing STRIPE_SECRET_KEY environment variable');
}

// Create Stripe instance only if we have a valid key (not during build time)
let stripe: Stripe | null = null;
if (stripeSecretKey && !stripeSecretKey.includes('dummy_key_for_build')) {
  stripe = new Stripe(stripeSecretKey, {
    apiVersion: '2023-10-16' as any,
  });
}

/**
 * Handle Stripe webhook events
 */
export async function POST(req: Request) {
  // Return error if Stripe is not initialized
  if (!stripe) {
    console.error('Stripe is not initialized. Check your API keys.');
    return NextResponse.json(
      { error: 'Stripe is not properly configured' },
      { status: 500 }
    );
  }

  const payload = await req.text();
  const sig = req.headers.get('stripe-signature') as string;

  let event: Stripe.Event;

  try {
    // Verify the event came from Stripe
    if (endpointSecret) {
      event = stripe.webhooks.constructEvent(payload, sig, endpointSecret);
    } else {
      // For testing without a webhook secret
      event = JSON.parse(payload) as Stripe.Event;
      console.warn('Webhook signature verification bypassed. This should only happen in development.');
    }
  } catch (err) {
    console.error('Webhook signature verification failed:', err);
    return NextResponse.json(
      { error: `Webhook Error: ${err instanceof Error ? err.message : 'Unknown error'}` },
      { status: 400 }
    );
  }

  // Handle the checkout.session.completed event
  if (event.type === 'checkout.session.completed') {
    try {
      const session = event.data.object as Stripe.Checkout.Session;
      console.log('Processing completed checkout session:', session.id);
      
      // Get product information from metadata or line items
      const productType = session.metadata?.productType || 'standard';
      const productId = session.metadata?.productId || 'exif-hound';
      
      // Generate different license keys based on product type
      const licensePrefix = productType === 'pro' ? 'EXHPRO-' : 'EXH-';
      const licenseKey = generateLicenseKey(licensePrefix);
      
      // One year from now
      const expirationDate = new Date();
      expirationDate.setFullYear(expirationDate.getFullYear() + 1);
      
      // Save the license
      await saveLicense({
        id: '',  // Will be generated by the saveLicense function
        key: licenseKey,
        email: session.customer_details?.email || undefined,
        productId,
        createdAt: new Date().toISOString(),
        expiresAt: expirationDate.toISOString(),
        stripeSessionId: session.id,
        activated: false
      });
      
      console.log(`License generated: ${licenseKey} for session: ${session.id}`);
      
      // Here you would typically send an email with the license key
      // For now, we'll just log it
      console.log(`TODO: Send email to ${session.customer_details?.email} with license: ${licenseKey}`);
      
    } catch (error) {
      console.error('Error processing checkout session:', error);
      return NextResponse.json(
        { error: 'Failed to process checkout session' },
        { status: 500 }
      );
    }
  }

  return NextResponse.json({ received: true });
}

