#!/usr/bin/env sh
set -e

npm run lint --workspace=exif-hound-desktop
npm run typecheck --workspace=exif-hound-desktop
npm test --workspace=exif-hound-desktop -- --runInBand
npm run build --workspace=exif-hound-desktop
